let C = prompt("Conversion en Farhenheit")
let calc = (C* 9/5 + 32)
document.write("Résultat :");
document.write("<br>")
document.write("1 Celsius vaut 33.8 Farhenheit")
document.write("<br>")
document.write(C + " Celsius = " + calc + " Farhenheit" )
document.write("<br>")
document.write(" 1 Farhenheit vaut 33.8 Celsius")
document.write("<br>")
document.write(calc + " Farhenheit = " + C + " Celsius" )